{
  "result": "fail",
  "errorCode": 2,
  "message": "some exception occurred"
}
